### ISSUE TITLE
Notion - Deprecation warning / Munki recipe

### ISSUE THREAD

**Issue by blainea-ca** [autopkg/swy-recipes#12]
Hello,

I noticed the deprecation warning for Notion 

> The resulting munki install from the Notion pkgs now lead to an app that complains about improper installation. Pull requests welcome.  Without a solution, Notion recipes will be retired in February 2021.

I use [Notion.jss.recipe](https://github.com/autopkg/crystalllized-recipes/blob/master/Notion/Notion.jss.recipe) and the parents [Notion.download.recipe](https://github.com/autopkg/swy-recipes/blob/master/Notion%20Labs%2C%20Inc./Notion.download.recipe), and [Notion.pkg.recipe](https://github.com/autopkg/swy-recipes/blob/master/Notion%20Labs%2C%20Inc./Notion.pkg.recipe)

The improper installation issue with the [Notion.munki.recipe](https://github.com/autopkg/swy-recipes/blob/master/Notion%20Labs%2C%20Inc./Notion.munki.recipe) is likely related to PR #8 which I added a set permissions of 0775 for the pkg. I don’t have Munki infrastructure for testing and I’m not clear if we can add a chmod 0775 from a DMG install or if this Munki recipe needs to be rewritten to install from pkg.

If anyone can provide feedback that would be greatly appreciated. Alternatively, we could rewrite the Munki recipe to install from pkg.

**Comment by swy** [comment]
I'd happily take input on how to address this.  Your PR definitely addressed install quirks at that time, but they've invoked new ones.

**Comment by blainea-ca** [comment]
I have two branches that are ready to be tested.

[blainea-ca/swy-recipes/tree/notion](https://github.com/blainea-ca/swy-recipes/tree/notion) based on [Zoom.munki.recipe](https://github.com/autopkg/homebysix-recipes/blob/master/Zoom/Zoom.munki.recipe) and uses the pkg install method for Notion.munki.recipe. I'm not clear if this faux_root is required.

[blainea-ca/swy-recipes/tree/notion-postinstall](https://github.com/blainea-ca/swy-recipes/tree/notion-postinstall) based on the fixes in [Spotify.munki.recipe](https://github.com/autopkg/recipes/blob/master/Spotify/Spotify.munki.recipe). This may require additional changes but should be possible with a post-install script.

If you are able to test I can create a PR if this works.

**Comment by swy** [comment]
Closed with a contribution from blainea-ca.
