### ISSUE TITLE
Notion.download recipe no longer fetches most recent version of Notion desktop app

### ISSUE THREAD

**Issue by deesweet** [autopkg/swy-recipes#4]
Hi there! It appears that Notion has switched from using https://desktop-release.notion-static.com/latest-mac.json to https://desktop-release.notion-static.com/latest-mac.yml as their "update feed." Since the Notion.download recipe parses the JSON file to determine whether to download a new version of Notion, the recipe is no longer fetching the most up-to-date version when run. Curiously, they've left the JSON doc up with an out-of-date version of Notion, so the recipe does not fail in its current state.

I'm not sure what's involved with parsing YAML vs JSON with AutoPkg download recipes - perhaps it would require a custom Python script or something of that nature somewhere in the workflow. I'll take a look and try to open a PR when I have the bandwidth to do so but thought I should note this.

**Comment by blainea-ca** [comment]
This issue was resolved with PR https://github.com/autopkg/swy-recipes/pull/5 and can be closed.

**Comment by swy** [comment]
Right, it was- I neglected to update that info here.  Thanks.
